const creditRatings = [
  { iso2: 'AL', sp: 'BB', moodys: 'Ba3' },
  { iso2: 'AD', sp: 'A-', fitch: 'A-' },
  { iso2: 'AO', sp: 'B-', fitch: 'B-', moodys: 'B3' },
  { iso2: 'AR', sp: 'CCC+', fitch: 'CCC+', moodys: 'Caa1' },
  { iso2: 'AM', sp: 'BB-', fitch: 'BB-', moodys: 'Ba3' },
  { iso2: 'AU', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'AT', sp: 'AA+', fitch: 'AA', moodys: 'Aa1' },
  { iso2: 'AZ', sp: 'BB+', fitch: 'BBB-', moodys: 'Ba1' },
  { iso2: 'BS', sp: 'BB-', fitch: 'BB-', moodys: 'B1' },
  { iso2: 'BH', sp: 'B', fitch: 'B', moodys: 'B2' },
  { iso2: 'BD', sp: 'B+', fitch: 'B+', moodys: 'B1' },
  { iso2: 'BB', sp: 'B+', fitch: 'B+', moodys: 'B3' },
  { iso2: 'BY', moodys: 'C' },
  { iso2: 'BE', sp: 'AA', fitch: 'A+', moodys: 'Aa3' },
  { iso2: 'BZ', sp: 'B-', moodys: 'Caa2' },
  { iso2: 'BJ', sp: 'BB-', fitch: 'B+', moodys: 'B1' },
  { iso2: 'BO', sp: 'CCC-', fitch: 'CCC', moodys: 'Caa1' },
  { iso2: 'BA', sp: 'B+', moodys: 'B3' },
  { iso2: 'BW', sp: 'BBB', moodys: 'A3' },
  { iso2: 'BR', sp: 'BB', fitch: 'BB', moodys: 'Ba1' },
  { iso2: 'BG', sp: 'BBB+', fitch: 'BBB+', moodys: 'Baa1' },
  { iso2: 'BF', sp: 'CCC+' },
  { iso2: 'KH', moodys: 'B2' },
  { iso2: 'CM', sp: 'B-', fitch: 'B', moodys: 'Caa1' },
  { iso2: 'CA', sp: 'AAA', fitch: 'AA+', moodys: 'Aaa' },
  { iso2: 'CV', sp: 'B', fitch: 'B' },
  { iso2: 'TD', sp: 'B-' },
  { iso2: 'CL', sp: 'A', fitch: 'A-', moodys: 'A2' },
  { iso2: 'CN', sp: 'A+', fitch: 'A', moodys: 'A1' },
  { iso2: 'CO', sp: 'BB', fitch: 'BB', moodys: 'Baa2' },
  { iso2: 'CG', sp: 'CCC+', fitch: 'CCC+', moodys: 'Caa2' },
  { iso2: 'CR', sp: 'BB', fitch: 'BB', moodys: 'Ba3' },
  { iso2: 'CI', sp: 'BB', fitch: 'BB', moodys: 'Ba3' },
  { iso2: 'HR', sp: 'A', fitch: 'A-', moodys: 'A3' },
  { iso2: 'CY', sp: 'A-', fitch: 'A-', moodys: 'A3' },
  { iso2: 'CZ', sp: 'AA-', fitch: 'AA-', moodys: 'Aa3' },
  { iso2: 'CD', sp: 'B-', moodys: 'B3' },
  { iso2: 'DK', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'DO', sp: 'BB', fitch: 'BB-', moodys: 'Ba3' },
  { iso2: 'EC', sp: 'B-', fitch: 'B-', moodys: 'Caa3' },
  { iso2: 'EG', sp: 'B', fitch: 'B', moodys: 'Caa1' },
  { iso2: 'SV', sp: 'B-', fitch: 'B-', moodys: 'B3' },
  { iso2: 'EE', sp: 'A+', fitch: 'A+', moodys: 'A1' },
  { iso2: 'SZ', moodys: 'B3' },
  { iso2: 'ET', moodys: 'Caa3' },
  { iso2: 'FJ', sp: 'B+', moodys: 'B1' },
  { iso2: 'FI', sp: 'AA+', fitch: 'AA', moodys: 'Aa1' },
  { iso2: 'FR', sp: 'A+', fitch: 'A+', moodys: 'Aa3' },
  { iso2: 'GA', fitch: 'CCC-', moodys: 'Caa1' },
  { iso2: 'GE', sp: 'BB', fitch: 'BB', moodys: 'Ba2' },
  { iso2: 'DE', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'GH', sp: 'B-', fitch: 'B-', moodys: 'Caa3' },
  { iso2: 'GR', sp: 'BBB', fitch: 'BBB', moodys: 'Baa3' },
  { iso2: 'GT', sp: 'BB+', fitch: 'BB+', moodys: 'Ba1' },
  { iso2: 'GN', sp: 'B+' },
  { iso2: 'HN', sp: 'BB-', moodys: 'B1' },
  { iso2: 'HU', sp: 'BBB-', fitch: 'BBB', moodys: 'Ba1' },
  { iso2: 'IS', sp: 'A+', moodys: 'A1' },
  { iso2: 'IN', sp: 'BBB', fitch: 'BBB-', moodys: 'Baa3' },
  { iso2: 'ID', sp: 'BBB', fitch: 'BBB', moodys: 'Baa2' },
  { iso2: 'IQ', sp: 'B-', fitch: 'B-', moodys: 'Caa1' },
  { iso2: 'IE', sp: 'AA+', fitch: 'AA', moodys: 'Aa3' },
  { iso2: 'IL', sp: 'A', fitch: 'A', moodys: 'Baa1' },
  { iso2: 'IT', sp: 'BBB+', fitch: 'BBB+', moodys: 'Baa2' },
  { iso2: 'JM', sp: 'BB', fitch: 'BB-', moodys: 'B1' },
  { iso2: 'JP', sp: 'A+', fitch: 'A', moodys: 'A1' },
  { iso2: 'JO', sp: 'BB-', fitch: 'BB-', moodys: 'B1' },
  { iso2: 'KZ', sp: 'BBB-', fitch: 'BBB', moodys: 'Baa1' },
  { iso2: 'KE', sp: 'B', fitch: 'B-', moodys: 'B3' },
  { iso2: 'XK', fitch: 'BB-' },
  { iso2: 'KW', sp: 'AA-', fitch: 'AA-', moodys: 'A1' },
  { iso2: 'KG', sp: 'B+', fitch: 'B', moodys: 'B3' },
  { iso2: 'LA', sp: 'CCC+', fitch: 'CCC+' },
  { iso2: 'LV', sp: 'A', fitch: 'A-', moodys: 'A3' },
  { iso2: 'LB', moodys: 'C' },
  { iso2: 'LS', fitch: 'B' },
  { iso2: 'LI', sp: 'AAA' },
  { iso2: 'LT', sp: 'A', fitch: 'A', moodys: 'A2' },
  { iso2: 'LU', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'MG', sp: 'B-' },
  { iso2: 'MY', sp: 'A-', fitch: 'BBB+', moodys: 'A3' },
  { iso2: 'MV', fitch: 'CC', moodys: 'Caa2' },
  { iso2: 'ML', moodys: 'Caa2' },
  { iso2: 'MT', sp: 'A-', fitch: 'A+', moodys: 'A2' },
  { iso2: 'MU', sp: 'BBB-', moodys: 'Baa3' },
  { iso2: 'MX', sp: 'BBB', fitch: 'BBB-', moodys: 'Baa2' },
  { iso2: 'MD', sp: 'BB-', fitch: 'B+', moodys: 'B2' },
  { iso2: 'MN', sp: 'BB-', fitch: 'B+', moodys: 'B3' },
  { iso2: 'ME', sp: 'B+', moodys: 'Ba3' },
  { iso2: 'MA', sp: 'BBB-', fitch: 'BB+', moodys: 'Ba1' },
  { iso2: 'MZ', sp: 'CCC+', fitch: 'CCC', moodys: 'Caa2' },
  { iso2: 'NA', fitch: 'BB-', moodys: 'B1' },
  { iso2: 'NP', fitch: 'BB-' },
  { iso2: 'NL', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'NZ', sp: 'AA+', fitch: 'AA+', moodys: 'Aaa' },
  { iso2: 'NI', sp: 'B+', fitch: 'B', moodys: 'B3' },
  { iso2: 'NG', sp: 'B-', fitch: 'B', moodys: 'Caa1' },
  { iso2: 'MK', sp: 'BB-', fitch: 'BB+' },
  { iso2: 'NO', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'OM', sp: 'BBB-', fitch: 'BBB-', moodys: 'Baa3' },
  { iso2: 'PK', sp: 'B-', fitch: 'B-', moodys: 'Caa1' },
  { iso2: 'PA', sp: 'BBB-', fitch: 'BB+', moodys: 'Baa3' },
  { iso2: 'PG', sp: 'B-', moodys: 'B2' },
  { iso2: 'PY', sp: 'BBB-', fitch: 'BB+', moodys: 'Baa3' },
  { iso2: 'PE', sp: 'BBB-', fitch: 'BBB', moodys: 'Baa1' },
  { iso2: 'PH', sp: 'BBB+', fitch: 'BBB', moodys: 'Baa2' },
  { iso2: 'PL', sp: 'A-', fitch: 'A-', moodys: 'A2' },
  { iso2: 'PT', sp: 'A+', fitch: 'A', moodys: 'A3' },
  { iso2: 'QA', sp: 'AA', fitch: 'AA', moodys: 'Aa3' },
  { iso2: 'RO', sp: 'BBB-', fitch: 'BBB-', moodys: 'Baa3' },
  { iso2: 'RW', sp: 'B+', fitch: 'B+', moodys: 'B2' },
  { iso2: 'VC', moodys: 'B3' },
  { iso2: 'SM', sp: 'BBB+', fitch: 'BBB-' },
  { iso2: 'SA', sp: 'A+', fitch: 'A+', moodys: 'Aa3' },
  { iso2: 'SN', sp: 'CCC+', moodys: 'Ba3' },
  { iso2: 'RS', sp: 'BBB-', fitch: 'BB+', moodys: 'Ba2' },
  { iso2: 'SC', fitch: 'BB' },
  { iso2: 'SG', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'SK', sp: 'A+', fitch: 'A-', moodys: 'A3' },
  { iso2: 'SI', sp: 'AA', fitch: 'A+', moodys: 'A3' },
  { iso2: 'ZA', sp: 'BB', fitch: 'BB-', moodys: 'Ba2' },
  { iso2: 'KR', sp: 'AA', fitch: 'AA-', moodys: 'Aa2' },
  { iso2: 'ES', sp: 'A+', fitch: 'A', moodys: 'A3' },
  { iso2: 'LK', sp: 'CCC+', fitch: 'CCC+', moodys: 'Caa1' },
  { iso2: 'SR', sp: 'CCC+', moodys: 'Caa3' },
  { iso2: 'SE', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'CH', sp: 'AAA', fitch: 'AAA', moodys: 'Aaa' },
  { iso2: 'TW', sp: 'AA+', fitch: 'AA', moodys: 'Aa3' },
  { iso2: 'TJ', sp: 'B', moodys: 'B3' },
  { iso2: 'TZ', fitch: 'B+' },
  { iso2: 'TH', sp: 'BBB+', fitch: 'BBB+', moodys: 'Baa1' },
  { iso2: 'TG', sp: 'B+' },
  { iso2: 'TT', sp: 'BBB-', moodys: 'Ba2' },
  { iso2: 'TN', fitch: 'B-', moodys: 'Caa1' },
  { iso2: 'TR', sp: 'BB-', fitch: 'BB-', moodys: 'B1' },
  { iso2: 'TM', fitch: 'BB-' },
  { iso2: 'UG', sp: 'B-', fitch: 'B', moodys: 'B2' },
  { iso2: 'UA', sp: 'CCC+', fitch: 'CCC', moodys: 'Ca' },
  { iso2: 'AE', sp: 'AA', fitch: 'AA-', moodys: 'Aa2' },
  { iso2: 'GB', sp: 'AA', fitch: 'AA-', moodys: 'Aa3' },
  { iso2: 'US', sp: 'AA+', fitch: 'AA+', moodys: 'Aa1' },
  { iso2: 'UY', sp: 'BBB+', fitch: 'BBB', moodys: 'Baa1' },
  { iso2: 'UZ', sp: 'BB', fitch: 'BB', moodys: 'Ba3' },
  { iso2: 'VN', sp: 'BB+', fitch: 'BB+', moodys: 'Ba2' },
  { iso2: 'ZM', sp: 'CCC+', fitch: 'B-', moodys: 'Caa3' },
];

module.exports = creditRatings;